services:
  - type: web
    name: floor-composer-backend
    runtime: python
    region: oregon
    plan: free
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: |
      cd backend
      gunicorn api.main:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    rootDir: backend
    buildFilter:
      paths:
      - backend/**
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src/backend/src
      - key: DATABASE_PATH
        value: /opt/render/project/src/backend/data/arcelor_steel_deck_database.json

  - type: web
    name: floor-composer-frontend
    runtime: node
    region: oregon
    plan: free
    buildCommand: |
      cd frontend
      npm ci
      npm run build
    startCommand: |
      cd frontend
      npm start
    rootDir: frontend
    buildFilter:
      paths:
      - frontend/**
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://floor-composer-backend.onrender.com