services:
  - type: web
    name: floor-composer-backend
    runtime: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api.main:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src/src:/opt/render/project/src
      - key: DATABASE_PATH
        value: /opt/render/project/src/data/arcelor_steel_deck_database.json